#!/bin/bash
BASE="$(cd `dirname "$0"` && pwd)"

main () {
  local cmd="$1"
  case $cmd in
    'setup')
      shift
      setup "$@"
      ;;
    'build')
      shift
      build "$@"
      ;;
    'devserver')
      shift
      devserver "$@"
      ;;
    'clean')
      shift
      clean "$@"
      ;;
    * )
      echo "
Exiting without running any operations.
Possible operations include:

  setup - Install dependencies.
    Usage: ./manage.sh setup

  devserver - Run the deverserver for local development.
    Usage: ./manage.sh devserver

  clean - Remove everything generated by this script.
    Usage: ./manage.sh clean
            "
      ;;
  esac
}

setup () {
  if ! [ -d "$BASE/node_modules" ]; then
    cd "$BASE/"
    mkdir "$BASE/node_modules"
    npm install coffee-script
  fi
  if ! [ -d "$BASE/scripts/node_modules" ]; then
    cd "$BASE/scripts/"
    mkdir "$BASE/scripts/node_modules"
    npm install filepath
    npm install request
    cd "$BASE"
  fi
}

devserver () {
  setup
  bin/devserver
}

clean () {
  rm -rf "$BASE/node_modules/"
  rm -rf "$BASE/scripts/node_modules/"
}

main "$@"
